export const fake_list = [
  {
    id: 1,
    first_name: 'Curt',
    last_name: 'Andreazzi',
    email: 'candreazzi0@pinterest.com',
    gender: 'Genderqueer',
    username: 'Nannopterum harrisi',
  },
  {
    id: 2,
    first_name: 'Carolyn',
    last_name: 'Haskell',
    email: 'chaskell1@typepad.com',
    gender: 'Non-binary',
    username: 'Haliaeetus leucoryphus',
  },
  {
    id: 3,
    first_name: 'Lise',
    last_name: 'Flanner',
    email: 'lflanner2@taobao.com',
    gender: 'Genderfluid',
    username: 'Alopochen aegyptiacus',
  },
  {
    id: 4,
    first_name: 'Ronni',
    last_name: 'Gillise',
    email: 'rgillise3@weibo.com',
    gender: 'Non-binary',
    username: 'Columba palumbus',
  },
  {
    id: 5,
    first_name: 'Consalve',
    last_name: 'Gumm',
    email: 'cgumm4@yahoo.com',
    gender: 'Bigender',
    username: 'Anathana ellioti',
  },
  {
    id: 6,
    first_name: 'James',
    last_name: 'Hartropp',
    email: 'jhartropp5@skype.com',
    gender: 'Agender',
    username: 'Toxostoma curvirostre',
  },
  {
    id: 7,
    first_name: 'Gabbi',
    last_name: 'Mandell',
    email: 'gmandell6@jigsy.com',
    gender: 'Genderfluid',
    username: 'Cercopithecus aethiops',
  },
  {
    id: 8,
    first_name: 'Sunshine',
    last_name: 'Rizon',
    email: 'srizon7@google.ru',
    gender: 'Genderqueer',
    username: 'Chlamydosaurus kingii',
  },
  {
    id: 9,
    first_name: 'Chickie',
    last_name: 'Sansome',
    email: 'csansome8@redcross.org',
    gender: 'Male',
    username: 'Felis concolor',
  },
  {
    id: 10,
    first_name: 'Blinni',
    last_name: 'Postin',
    email: 'bpostin9@g.co',
    gender: 'Bigender',
    username: 'Macropus rufogriseus',
  },
  {
    id: 11,
    first_name: 'Dee dee',
    last_name: 'Makin',
    email: 'dmakina@tripadvisor.com',
    gender: 'Non-binary',
    username: 'Dicrostonyx groenlandicus',
  },
  {
    id: 12,
    first_name: 'Broddy',
    last_name: 'Klagges',
    email: 'bklaggesb@va.gov',
    gender: 'Bigender',
    username: 'Cacatua galerita',
  },
  {
    id: 13,
    first_name: 'Jany',
    last_name: 'Pietrasik',
    email: 'jpietrasikc@1und1.de',
    gender: 'Agender',
    username: 'Suricata suricatta',
  },
  {
    id: 14,
    first_name: 'Bay',
    last_name: 'Brimman',
    email: 'bbrimmand@who.int',
    gender: 'Male',
    username: 'Sylvicapra grimma',
  },
  {
    id: 15,
    first_name: 'Hermione',
    last_name: 'Reedshaw',
    email: 'hreedshawe@a8.net',
    gender: 'Non-binary',
    username: 'Macropus rufogriseus',
  },
  {
    id: 16,
    first_name: 'Barr',
    last_name: 'Heggs',
    email: 'bheggsf@ycombinator.com',
    gender: 'Male',
    username: 'Cacatua tenuirostris',
  },
];
